SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM users where id > 0;
DELETE FROM exercises where id > 0;
DELETE FROM users_exercises where id > 0;
DELETE FROM exercise_progress where id > 0;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO users (email) VALUES ('pesjak.matej@gmail.com');
SET @user1Id = LAST_INSERT_ID();
INSERT INTO users (email) VALUES ('katja.zalokar@gmail.com');
SET @user2Id = LAST_INSERT_ID();
INSERT INTO exercises (name, is_custom_exercise) VALUES ('bench_press', false);
SET @exercise1Id= LAST_INSERT_ID();
INSERT INTO exercises (name, is_custom_exercise) VALUES ('deadlift', false);
SET @exercise2Id= LAST_INSERT_ID();
INSERT INTO users_exercises (user_id, exercise_id) VALUES (@user1Id, @exercise1Id);
INSERT INTO exercise_progress (`sets`, reps, weight, weight_unit, user_exercise_id, date) VALUES (10, 10, 10, 'lbs', LAST_INSERT_ID(), NOW());
INSERT INTO users_exercises (user_id, exercise_id) VALUES (@user1Id, @exercise2Id);
INSERT INTO exercise_progress (`sets`, reps, weight, weight_unit, user_exercise_id, date) VALUES (10, 10, 10, 'lbs', LAST_INSERT_ID(), NOW());
INSERT INTO users_exercises (user_id, exercise_id) VALUES (@user2Id, @exercise1Id);
INSERT INTO exercise_progress (`sets`, reps, weight, weight_unit, user_exercise_id, date) VALUES (10, 10, 10, 'lbs', LAST_INSERT_ID(), NOW());
INSERT INTO users_exercises (user_id, exercise_id) VALUES (@user2Id, @exercise2Id);
INSERT INTO exercise_progress (`sets`, reps, weight, weight_unit, user_exercise_id, date) VALUES (10, 10, 10, 'lbs', LAST_INSERT_ID(), NOW());
